# download_data:
#   url: mursideyarkin/mobile-games-ab-testing-cookie-cats
#   local_path: data/cookie_cats/raw
# extract_data:
#   local_path: data/cookie_cats/raw
#   output_path: data/cookie_cats/info
preprocess_data:
  local_path: data/cookie_cats/raw
  output_path: data/cookie_cats/processed
  target_columns:
    # if target column is not defined, it will be assigned as all columns
    - 'sum_gamerounds'
    - 'retention_1'
    - 'retention_7'
    - 'version'
  outlier: 
    # use only the method you want to apply
    - method: 'remove-top-k'
      value: 1
      columns: ['sum_gamerounds']
    - method: 'remove-bottom-k'
      value: 0
      columns: []
    - method: 'remove-top-percent'
      value: 0.00
      columns: []
    - method: 'remove-bottom-percent'
      value: 0.00
      columns: []
  missing: 
    # use only the method you want to apply
    - method: 'drop-row'
      columns: ['all'] 
    - method: 'drop-column'
      columns: []
    - method: 'fill-mean'
      columns: []
    - method: 'fill-median'
      columns: []
    - method: 'fill-mode'
      columns: []
    - method: 'fill-constant'
      columns: []
      value: 0
    - method: 'fill-forward'
      columns: []
    - method: 'fill-backward'
      columns: []
    - method: 'fill-interpolate'
      columns: []
      