name: Python CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/kaggle_projects" >> $GITHUB_ENV

      - name: Decode and write kaggle.json
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON_B64 }}" | base64 --decode > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Run tests in base project
        working-directory: kaggle_projects/base
        run: |
          uv pip install -r requirements.txt
          uv run pytest tests

      - name: Run tests in titanic project
        working-directory: kaggle_projects/titanic
        run: |
          uv pip install -r requirements.txt
          uv run pytest tests
